name: TagBot
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
    inputs:
      lookback:
        default: "3"
jobs:
  TagBot:
    permissions:
      issues: write
      contents: write
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Edit the following line to reflect the actual name of the GitHub Secret containing your private key
          ssh: ${{ secrets.SSH_KEY }}
          registry: DIII-D/D3DRegistry.jl
        env:
          registry_ssh: ${{ secrets.REGISTRY_SSH_KEY }}